//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PitWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дефект
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> id_ВТД { get; set; }
        public Nullable<System.Guid> id_ДДО { get; set; }
        public Nullable<System.Guid> id_Ремонта { get; set; }
        public Nullable<int> id_признак_состояния { get; set; }
        public Nullable<System.Guid> id_объекта { get; set; }
    
        public virtual Внутритрубная_диагностика Внутритрубная_диагностика { get; set; }
        public virtual ДДО ДДО { get; set; }
        public virtual Объект Объект { get; set; }
        public virtual Признак_состояния_работы Признак_состояния_работы { get; set; }
        public virtual Ремонт Ремонт { get; set; }
    }
}
