//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PitWorks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public System.Guid id { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int id_уровня_доступа { get; set; }
        public Nullable<int> id_ЛПУ { get; set; }
    
        public virtual ЛПУ ЛПУ { get; set; }
        public virtual Уровни_доступа Уровни_доступа { get; set; }
    }
}
